version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [test-commands-master]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: mfykmn/terraform
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-workflow:
          ssh-fingerprints: 31:2d:b7:ba:4c:d1:70:45:24:09:b1:4d:2e:5d:12:b4
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master
      - orb-tools/trigger-integration-workflow:
          ssh-fingerprints: 31:2d:b7:ba:4c:d1:70:45:24:09:b1:4d:2e:5d:12:b4
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      - orb-tools/pack:
          name: pack-dev
          filters: *integration-dev_filters

      - orb-tools/pack:
          name: pack-master
          filters: *integration-master_filters

      - orb-tools/test-in-builds:
          attach-workspace: true
          orb-name: terraform
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: test/test.yml
          name: test-commands-dev
          filters: *integration-dev_filters
          requires:
            - pack-dev

      - orb-tools/test-in-builds:
          attach-workspace: true
          orb-name: terraform
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: test/test.yml
          name: test-commands-master
          filters: *integration-master_filters
          requires:
            - pack-master

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          orb-name: mfykmn/terraform
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          orb-name: mfykmn/terraform
          release: minor
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          orb-name: mfykmn/terraform
          release: major
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
