version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: mafuyuk/terraform
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-workflow:
          ssh-fingerprints: 31:2d:b7:ba:4c:d1:70:45:24:09:b1:4d:2e:5d:12:b4
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master
      - orb-tools/trigger-integration-workflow:
          ssh-fingerprints: 31:2d:b7:ba:4c:d1:70:45:24:09:b1:4d:2e:5d:12:b4
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master
