parameters:
  tag:
    description: docker image tag
    type: string
    default: latest

docker:
  - image: hashicorp/terraform:<< parameters.tag >>

environment:
  - TF_PLUGIN_CACHE_DIR: .terraform.d/plugin-cache
