parameters:
  tag:
    type: string
    default: latest
    description: |
      docker image tag

docker:
  - image: hashicorp/terraform:<< parameters.tag >>

environment:
  - TF_PLUGIN_CACHE_DIR: .terraform.d/plugin-cache
